SoftDevIV-US/llama-gamer

.github/CODEOWNERS, .vscode/extensions.json, .vscode/settings.json
=> chore: add codeowners

package.json, release.config.js
=> chore: improve package json and release configuration

package.json, release.config.js
=> chore: update package json configuration

projects/api/package.json, projects/api/prisma/schema.prisma, projects/api/src/app.module.ts, projects/api/src/countries/countries.controller.ts, projects/api/src/countries/countries.module.ts, projects/api/src/countries/countries.service.ts, projects/api/src/countries/dto/create-country.dto.ts, projects/api/src/countries/dto/update-country.dto.ts, projects/api/src/countries/entities/country.entity.ts, projects/api/src/main.ts, projects/api/test/countries/countries.controller.spec.ts, projects/api/test/countries/countries.service.spec.ts, projects/api/test/test.spec.ts
=> feat: add countries backend

projects/api/prisma/schema.prisma, projects/api/src/app.module.ts, projects/api/src/brand/brand.controller.ts, projects/api/src/brand/brand.module.ts, projects/api/src/brand/brand.service.ts, projects/api/src/brand/dto/create-brand.dto.ts, projects/api/src/brand/dto/update-brand.dto.ts, projects/api/src/brand/entities/brand.entity.ts, projects/api/src/countries/countries.service.ts, projects/api/src/countries/entities/country.entity.ts, projects/api/test/brands/brand.controller.spec.ts, projects/api/test/brands/brand.service.spec.ts, projects/api/tsconfig.json
PBI 33 
Implement the CRUD of the brand
- [x ] ✨ New feature (non-breaking change which adds functionality)
=> feat: add brand backend

projects/api/prisma/schema.prisma, projects/api/src/app.module.ts, projects/api/src/brand/brand.module.ts, projects/api/src/brand/dto/create-brand.dto.ts, projects/api/src/brand/dto/update-brand.dto.ts, projects/api/src/brand/entities/brand.entity.ts, projects/api/src/category/category.controller.ts, projects/api/src/category/category.module.ts, projects/api/src/category/category.service.ts, projects/api/src/category/dto/create-category.dto.ts, projects/api/src/category/dto/update-category.dto.ts, projects/api/src/category/entities/category.entity.ts, projects/api/src/countries/countries.controller.ts, projects/api/src/countries/dto/create-country.dto.ts, projects/api/src/countries/dto/update-country.dto.ts, projects/api/src/countries/entities/country.entity.ts, projects/api/src/utils/constants.ts, projects/api/test/brands/brand.service.spec.ts, projects/api/test/category/category.controller.spec.ts, projects/api/test/category/category.service.spec.ts
=> feat: add categories backend

pnpm-lock.yaml, projects/client/.eslintrc.cjs, projects/client/package.json, projects/client/src/app/components/button/Button.tsx, projects/client/src/app/components/field/Field.tsx, projects/client/src/app/components/form/Form.tsx, projects/client/src/app/components/header/Header.tsx, projects/client/src/app/components/input-field/InputField.tsx, projects/client/src/app/components/line/Line.tsx, projects/client/src/app/components/list/List.tsx, projects/client/src/app/components/not-found/NotFound.tsx, projects/client/src/app/components/remove/Remove.tsx, projects/client/src/app/layouts/Layout.tsx, projects/client/src/app/pages/countries/Countries.tsx, projects/client/src/app/pages/countries/hooks/useLoadCountries.ts, projects/client/src/app/pages/countries/pages/add/AddCountry.tsx, projects/client/src/app/pages/countries/pages/add/hooks/useAddCountry.ts, projects/client/src/app/pages/countries/pages/edit/EditCountry.tsx, projects/client/src/app/pages/countries/pages/edit/hooks/useEditCountry.ts, projects/client/src/app/pages/countries/pages/info/CountryInfo.tsx, projects/client/src/app/pages/countries/pages/info/hooks/useLoadCountryInfo.ts, projects/client/src/app/pages/countries/pages/remove/RemoveCountry.tsx, projects/client/src/app/pages/countries/pages/remove/hooks/useRemoveCountry.ts, projects/client/src/app/pages/not-found/NotFound.tsx
=> feat: add countries remove countries and edit countries

pnpm-lock.yaml, projects/client/.eslintrc.cjs, projects/client/package.json, projects/client/src/app/components/button/Button.tsx, projects/client/src/app/components/field/Field.tsx, projects/client/src/app/components/form/Form.tsx, projects/client/src/app/components/header/Header.tsx, projects/client/src/app/components/input-field/InputField.tsx, projects/client/src/app/components/line/Line.tsx, projects/client/src/app/components/list/List.tsx, projects/client/src/app/components/not-found/NotFound.tsx, projects/client/src/app/components/remove/Remove.tsx, projects/client/src/app/layouts/Layout.tsx, projects/client/src/app/pages/countries/Countries.tsx, projects/client/src/app/pages/countries/hooks/useLoadCountries.ts, projects/client/src/app/pages/countries/pages/add/AddCountry.tsx, projects/client/src/app/pages/countries/pages/add/hooks/useAddCountry.ts, projects/client/src/app/pages/countries/pages/edit/EditCountry.tsx, projects/client/src/app/pages/countries/pages/edit/hooks/useEditCountry.ts, projects/client/src/app/pages/countries/pages/info/CountryInfo.tsx, projects/client/src/app/pages/countries/pages/info/hooks/useLoadCountryInfo.ts, projects/client/src/app/pages/countries/pages/remove/RemoveCountry.tsx, projects/client/src/app/pages/countries/pages/remove/hooks/useRemoveCountry.ts, projects/client/src/app/pages/not-found/NotFound.tsx
=> feat: add countries edit countries and remove countries

projects/client/src/app/App.tsx, projects/client/src/app/pages/brands/Brands.tsx, projects/client/src/app/pages/brands/hooks/useLoadBrands.ts, projects/client/src/app/pages/brands/pages/add/AddBrand.tsx, projects/client/src/app/pages/brands/pages/add/hooks/useAddCountry.ts, projects/client/src/app/pages/brands/pages/edit/EditBrand.tsx, projects/client/src/app/pages/brands/pages/edit/hooks/useEditBrand.ts, projects/client/src/app/pages/brands/pages/info/BrandInfo.tsx, projects/client/src/app/pages/brands/pages/info/hooks/useLoadBrandInfo.ts, projects/client/src/models/brand.model.ts, projects/client/src/services/brand.service.ts, projects/client/test/brand/brand.service.spec.ts
Adding the brands list
- [x ] ✨ New feature (non-breaking change which adds functionality)
=> feat: add brand list

projects/api/.eslintrc.js, projects/api/src/brand/dto/create-brand.dto.ts, projects/api/src/brand/dto/update-brand.dto.ts, projects/api/src/category/dto/create-category.dto.ts, projects/api/src/category/dto/update-category.dto.ts, projects/api/src/country/dto/create-country.dto.ts, projects/api/src/country/dto/update-country.dto.ts, projects/api/src/utils/constants.ts, projects/client/src/app/components/header/Header.tsx, projects/client/src/app/components/input-field/InputField.tsx, projects/client/src/app/components/list/List.tsx, projects/client/src/app/layouts/InnerLayout.tsx, projects/client/src/app/pages/countries/pages/add/AddCountry.tsx, projects/client/src/app/pages/countries/pages/edit/EditCountry.tsx
=> fix: bugs 71 70 69 68 67 64

projects/api/.eslintrc.js, projects/api/prisma/schema.prisma, projects/api/src/app.module.ts, projects/api/src/brand/dto/create-brand.dto.ts, projects/api/src/brand/dto/update-brand.dto.ts, projects/api/src/category/dto/create-category.dto.ts, projects/api/src/category/dto/update-category.dto.ts, projects/api/src/country/dto/create-country.dto.ts, projects/api/src/country/dto/update-country.dto.ts, projects/api/src/suppliers/dto/create-supplier.dto.ts, projects/api/src/suppliers/dto/update-supplier.dto.ts, projects/api/src/suppliers/entities/supplier.entity.ts, projects/api/src/suppliers/suppliers.controller.ts, projects/api/src/suppliers/suppliers.module.ts, projects/api/src/suppliers/suppliers.service.ts, projects/api/src/utils/constants.ts, projects/api/test/suppliers/suppliers.controller.spec.ts, projects/api/test/suppliers/suppliers.service.spec.ts, projects/client/src/app/components/header/Header.tsx, projects/client/src/app/components/input-field/InputField.tsx, projects/client/src/app/components/list/List.tsx, projects/client/src/app/layouts/InnerLayout.tsx, projects/client/src/app/pages/countries/pages/add/AddCountry.tsx, projects/client/src/app/pages/countries/pages/add/hooks/useAddCountry.ts, projects/client/src/app/pages/countries/pages/edit/EditCountry.tsx, projects/client/src/app/pages/countries/pages/edit/hooks/useEditCountry.ts
=> fix: bugs related to us 59 61

projects/api/src/suppliers/dto/create-supplier.dto.ts, projects/api/src/suppliers/suppliers.service.ts, projects/api/test/suppliers/suppliers.service.spec.ts
=> fix: bug 75 related to us 34

projects/client/src/app/App.tsx, projects/client/src/app/components/footer/Footer.tsx, projects/client/src/app/pages/about/about.tsx, projects/client/src/app/pages/account/account.tsx, projects/client/src/app/pages/cart/cart.tsx, projects/client/src/app/pages/contact/contact.tsx, projects/client/src/app/pages/home/user/User.tsx, projects/client/src/app/pages/termsConditions/TermsConditions.tsx, projects/client/src/app/pages/wishlist/wishList.tsx
=> fix: bugs 81-82-83-84-85-86-87-88-89-90-91 pbi-30

projects/client/src/app/pages/suppliers/Suppliers.tsx
=> fix: issue 97 of the us 54

projects/api/src/suppliers/dto/create-supplier.dto.ts, projects/api/src/suppliers/suppliers.service.ts, projects/api/test/suppliers/suppliers.service.spec.ts, projects/client/src/app/App.tsx, projects/client/src/app/components/footer/Footer.tsx, projects/client/src/app/components/input-image/InputImage.tsx, projects/client/src/app/pages/about/about.tsx, projects/client/src/app/pages/account/account.tsx, projects/client/src/app/pages/brands/pages/add/AddBrand.tsx, projects/client/src/app/pages/brands/pages/add/hooks/useAddBrand.ts, projects/client/src/app/pages/brands/pages/edit/EditBrand.tsx, projects/client/src/app/pages/brands/pages/edit/hooks/useEditBrand.ts, projects/client/src/app/pages/brands/pages/info/BrandInfo.tsx, projects/client/src/app/pages/brands/pages/info/hooks/useLoadBrandInfo.ts, projects/client/src/app/pages/cart/cart.tsx, projects/client/src/app/pages/contact/contact.tsx, projects/client/src/app/pages/home/user/User.tsx, projects/client/src/app/pages/suppliers/Suppliers.tsx, projects/client/src/app/pages/termsConditions/TermsConditions.tsx, projects/client/src/app/pages/wishlist/wishList.tsx
Im creating the forms for add and edit the brands information, also the generic component  fot the management of images
also development the information form.
- [x ] ✨ New feature (non-breaking change which adds functionality)
=> feat: pbi 38 add forms for brands

projects/api/src/suppliers/dto/create-supplier.dto.ts, projects/api/src/suppliers/dto/update-supplier.dto.ts, projects/client/src/app/pages/suppliers/pages/edit/hooks/useEditSupplier.ts
=> fix: bug 96 related to us 37 and add more validations for the supplier email field

projects/client/src/app/components/form/Form.tsx, projects/client/src/app/components/image-field/ImageField.tsx, projects/client/src/app/components/input-field/InputField.tsx, projects/client/src/app/components/list/List.tsx, projects/client/src/app/constants/constants.ts, projects/client/src/app/pages/categories/hooks/useLoadCategories.ts, projects/client/src/app/pages/categories/pages/add/AddCategory.tsx, projects/client/src/app/pages/categories/pages/add/hooks/useAddCategory.ts, projects/client/src/app/pages/categories/pages/edit/EditCategory.tsx, projects/client/src/app/pages/categories/pages/edit/hooks/useEditCategory.ts, projects/client/src/app/pages/categories/pages/info/CategoryInfo.tsx, projects/client/src/app/pages/categories/pages/info/hooks/useLoadCategoryInfo.ts, projects/client/src/app/pages/countries/pages/edit/EditCountry.tsx, projects/client/src/config/config.ts, projects/client/src/services/cloudinary.service.ts, projects/client/test/cloudinary/cloudinary.service.spec.ts
…d cloudinary service for categories
=> feat: pbi 39 and cloudinary service

projects/client/src/app/App.tsx, projects/client/src/app/pages/products/Products.tsx, projects/client/src/app/pages/products/hooks/useLoadProducts.ts, projects/client/src/app/pages/products/pages/add/AddProduct.tsx, projects/client/src/app/pages/products/pages/edit/EditProduct.tsx, projects/client/src/app/pages/products/pages/info/ProductInfo.tsx, projects/client/src/models/product.model.ts, projects/client/src/services/product.service.ts, projects/client/test/product/product.service.spec.ts
- [x ] ✨ New feature (non-breaking change which adds functionality)
=> feat: add products list

projects/client/src/app/components/input-image/InputImage.tsx, projects/client/src/app/pages/brands/pages/add/AddBrand.tsx, projects/client/src/app/pages/brands/pages/edit/EditBrand.tsx, projects/client/src/app/pages/brands/pages/edit/hooks/useEditBrand.ts, projects/client/src/app/pages/brands/pages/info/BrandInfo.tsx
- [x ] 🛠️ Bug fix (non-breaking change which fixes an issue)
=> fix: issue 100 and issue 102

projects/client/src/app/pages/products/pages/info/ProductInfo.tsx, projects/client/src/app/pages/products/pages/info/hooks/useLoadProductInfo.ts, projects/client/src/models/product.model.ts
=> feat: add product info

projects/client/src/app/pages/categories/pages/user-category/UserCategory.tsx, projects/client/src/app/pages/categories/pages/user-category/components/ProductByCategoryCard.tsx, projects/client/src/app/pages/categories/pages/user-category/hooks/useLoadProductsByCategory.ts, projects/client/src/app/pages/home/user/User.tsx, projects/client/src/models/product.model.ts
=> feat: add category page

projects/api/prisma/data/products.ts, projects/api/src/product/product.controller.ts, projects/api/src/product/product.service.ts, projects/client/src/app/pages/products/pages/user-product/UserProduct.tsx, projects/client/src/app/pages/products/pages/user-product/hooks/useLoadProductInfo.ts
=> feat: add product page

projects/client/src/app/pages/cart/components/TotalBalance.tsx, projects/client/src/app/pages/invoice/Invoice.tsx, projects/client/src/app/pages/invoice/InvoiceModal.tsx
- [x ] 🛠️ Bug fix (non-breaking change which fixes an issue)
=> fix: pdf flashes, pdf corrupt and tax calculation

projects/client/src/app/App.tsx, projects/client/src/app/pages/categories/pages/user-category/components/ProductByCategoryCard.tsx, projects/client/src/app/pages/products/pages/info/InfoProduct.tsx
=> fix: issue 116 product info page

projects/client/src/app/pages/cart/Cart.tsx, projects/client/src/app/pages/cart/components/ProductCart.tsx
=> fix: issue 112
